### ISSUE TITLE
現在進行中

### ISSUE THREAD

**Issue by next-fire-starter** [next-fire-starter/node-express-pg#3]
```yaml
start_date: 2022/7/1
due_date: 2022/7/6
progress: 0.1
parent: 2
```
